### ISSUE TITLE
The content sorting method of documents generated by Mac and Windows is inconsistent！！

### ISSUE THREAD

**Issue by qq1147050160** [rigwild/apidoc-markdown#27]
## Describe the bug

The content sorting method of documents generated by Mac and Windows is inconsistent

**Versions (please complete the following information):**

- `Node.js` version: `v16.14.2`
- `apidoc-markdown` version: `^7.2.5`

**Additional context**

**Comment by rigwild** [comment]
Are you talking about https://github.com/rigwild/apidoc-markdown#api-groups-order ?

Can you give an example?

**Comment by qq1147050160** [comment]
is in Table of contents! There is a significant difference in the sorting of documents generated by Mac and Windows. If possible, it is recommended that the author give it a try!

I originally planned to have API documentation automatically generate updates in Git Hooks. I have to give up this idea because of the differences in content!

Example of results on Windows：

- [session](#session)
  - [保持桌面会话（心跳）](#保持桌面会话（心跳）)
  - [创建桌面会话](#创建桌面会话)
  - [会话日志列表](#会话日志列表)
  - [结束桌面会话](#结束桌面会话)
  - [启动桌面会话](#启动桌面会话)

Example of results on Mac：

- [session](#session)
  - [会话日志列表](#会话日志列表)
  - [保持桌面会话（心跳）](#保持桌面会话（心跳）)
  - [创建桌面会话](#创建桌面会话)
  - [启动桌面会话](#启动桌面会话)
  - [结束桌面会话](#结束桌面会话)

**Comment by qq1147050160** [comment]
Due to differences in content, it is very easy to generate conflicts when merging code!

**Comment by rigwild** [comment]
I don't know how this could happen.

I suspect this is due to different handling of non-latin caracters by node.js in windows vs mac?

Anyway, you should be able to manually order them yourself using the `order` key, see https://github.com/rigwild/apidoc-markdown/blob/master/test/_testFiles/input/apidoc.json#L7-L20

I will close this as I don't think I can fix it easily (I don't have experience with non-latin characters)

**Comment by rigwild** [comment]
I suspect this is due to different handling of non-latin caracters by node.js in windows vs mac?

According to [this StackOverflow answer](https://stackoverflow.com/a/41692875), you can pass the locale to sorting function

I will close this as most of the users of this lib are using latin characters

You can fork this and use `arr.sort((x,y)=>x.localeCompare(y, 'zh-CN'))`, it may fix it.

https://github.com/rigwild/apidoc-markdown/blob/master/src/generator.ts#L59-L60
